<?php

/**
 * @file
 * Contains flysystem_gcs_cors.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flysystem_gcs_cors_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flysystem_gcs_cors module.
    case 'help.page.flysystem_gcs_cors':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow directly uploading to Google Cloud Storage from the web browser') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_info_alter().
 */
function flysystem_gcs_cors_field_info_alter(array &$info) {
  // Need to override the file and image fields
  // to allow setting uploads larger than what PHP allows
  // since we're avoiding PHP altogether and uploading directly to GCS
  // do not need to be constrained by PHP's memory limits.
  $info['file']['class'] = '\Drupal\flysystem_gcs_cors\Plugin\Field\FieldType\FlysystemGcsCorsFile';
  $info['image']['class'] = '\Drupal\flysystem_gcs_cors\Plugin\Field\FieldType\FlysystemGcsCorsImage';
}
